version: '3.9'

services:
  database:
    image: postgres:alpine
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/data/postgresql
    networks:
      - rentx_network
  app:
    restart: always
    build: .
    container_name: rentx
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    networks:
      - rentx_network
    depends_on:
      - database

volumes:
  pgdata:
    driver: local

networks:
  rentx_network:
    driver: bridge
